colorScheme = "Forest"
disableImageOptimization = false
defaultBackgroundImage = "image.jpg" # used as default for background images 

[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Tags"
  pageRef = "tags"
  weight = 30

[author]
   name = "ã‚‚ãˆã‹"
   image = "profile.jpg"
   headline = "æˆ‘è¿™è¾¹æ²¡æœ‰ä¸‹é›¨ï¼Œä½†å¿ƒé‡Œæ—©å·²æ³›èµ·äº†æ¶Ÿæ¼ª"
   bio = "èŒä½³ğŸ¨" #Â appears in author card for each article

[homepage]
  layout = "background" # valid options: page, profile, hero, card, background, custom
  homepageImage = "image.jpg" # used in: hero, and card
  showRecent = true
  showRecentItems = 6
  showMoreLink = true
  showMoreLinkDest = "/posts"
  cardView = true
  cardViewScreenWidth = false
  layoutBackgroundBlur = true # only used when layout equals background

[header]
  layout = "fixed"

[article]
  showHero = true
  heroStyle = "background" 
  showSummary = true
  showTableOfContents = true
  showRelatedContent = true
  relatedContentLimit = 3

[list]
  showCards = true
  groupByYear = false
  cardView = true
